import Head from "next/head";
import { allProjects, Project } from "contentlayer/generated";
import { compareDesc, format } from "date-fns";
import Link from "next/link";

type PageProps = {
  projects: Project[];
};

export async function getStaticProps() {
  const projects = allProjects.sort((a, b) => {
    return compareDesc(new Date(a.date), new Date(b.date));
  });

  return { props: { projects } };
}

function Home({ projects }: PageProps) {
  return (
    <div>
      <Head>
        <title>Danny Jiang</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/images/icons/Ramen.ico" />
      </Head>

      <main className="container mx-auto flex flex-col items-center gap-4">
        <div className="my-1 sm:mx-4 md:mt-20 md:max-w-7xl">
          <div className="flex justify-between gap-36">
            <div className="flex flex-col gap-4 text-left text-2xl">
              <h1 className="text-3xl font-bold">Welcome</h1>
              <div className="flex flex-col gap-4">
                <p>
                  Hi there! I'm Danny Jiang, a passionate web/game developer.
                  <br />
                  I'm a graduate at the Unversity of Technology Sydney studied a
                  Bachelor of Science in Games Development.
                </p>
                <div className="flex gap-4 text-lg">
                  <Link href="https://github.com/SV3N77">
                    <a>
                      <span className="rounded-full bg-black px-2 py-1 text-white">
                        Github
                      </span>
                    </a>
                  </Link>
                  <Link href="www.linkedin.com/in/danny-jiang2">
                    <a>
                      <span className="rounded-full bg-[#0072b1] px-2 py-1 text-white">
                        Linkedin
                      </span>
                    </a>
                  </Link>
                </div>
              </div>
            </div>
            <img
              src="/images/gifs/Computer.gif"
              alt="computer"
              className="aspect-square bg-cover"
            />
          </div>

          <div className="my-28 flex flex-col gap-8 text-lg">
            <h1 className="text-3xl font-bold">About</h1>
            <div className="flex items-center justify-around">
              <img
                src="/images/gifs/Kenji-Idle.gif"
                alt="game"
                className="aspect-square bg-cover"
              />

              <p className="md:max-w-2xl">
                I enjoy playing video games and learning new things. I'm always
                looking for new ways to improve my game development skills. I am
                mostly interested in the design aspect of game development and
                have been improving these skills with some of the projects i
                have done.
              </p>
            </div>
            <div className="flex items-center justify-around">
              <img
                src="/images/gifs/WebDev.gif"
                alt="web"
                className="aspect-square"
              />
              <p className="md:max-w-2xl">
                I enjoy learning new things and solving problems. I'm always
                looking for new ways to improve my coding skills. I am
                interested in front-end web development. I really enjoy making
                the website look asethetic as possible.
              </p>
            </div>
          </div>

          <section className="my-10 flex flex-col gap-4 pb-20">
            <h1 className="my-10 text-3xl font-bold" id="Projects">
              Projects
            </h1>
            <div className="grid gap-4 lg:grid-cols-2">
              {projects.map((project) => (
                <ProjectCards key={project._id} {...project} />
              ))}
            </div>
          </section>
        </div>
      </main>
    </div>
  );
}

export default Home;

// internal components

function ProjectCards({
  title,
  url,
  shortDescription,
  tags,
  date,
  images,
}: Project) {
  const newDate = format(new Date(date), "MMM yy");

  return (
    <Link href={url}>
      <a>
        <div className="flex h-60 overflow-hidden rounded-lg bg-slate-100 text-sm shadow-lg">
          <div className="aspect-video md:aspect-square md:w-auto">
            <img
              src={images?.at(0)?.src}
              className="aspect-square h-full w-full object-cover"
            />
          </div>
          <div className="flex grow flex-col gap-2">
            <h1 className="bg-teal-200 p-2 text-xl font-semibold">{title}</h1>
            <div className="flex flex-col gap-2 p-2 text-sm">
              <div className="">{newDate}</div>
              <div>{shortDescription}</div>
              <div className="mt-4 flex flex-wrap gap-2 text-xs">
                {tags.map((tag) => (
                  <span
                    key={tag}
                    className="rounded-full bg-teal-500 px-2 py-1 text-teal-100"
                  >
                    {tag}
                  </span>
                ))}
              </div>
            </div>
          </div>
        </div>
      </a>
    </Link>
  );
}
