import Head from "next/head";
import { allProjects, Project } from "contentlayer/generated";
import { compareDesc } from "date-fns";
import Link from "next/link";

type PageProps = {
  projects: Project[];
};

export async function getStaticProps() {
  const projects = allProjects.sort((a, b) => {
    return compareDesc(new Date(a.date), new Date(b.date));
  });

  return { props: { projects } };
}

function Home({ projects }: PageProps) {
  return (
    <div>
      <Head>
        <title>Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/images/icons/Ramen.ico" />
      </Head>

      <main className="container mx-auto flex flex-col items-center gap-4">
        <div className="my-1 sm:mx-4 md:mt-20 md:max-w-6xl">
          <div className="flex justify-between gap-36">
            <div className="flex flex-col gap-4 text-left text-2xl">
              <h1 className="text-3xl font-bold">Welcome</h1>
              <div className="flex gap-4">
                <p>
                  Hi there! I'm Danny Jiang, a passionate web/game developer.
                  <br />
                  I'm a graduate at the Unversity of Technology Sydney studied a
                  Bachelor of Science in Games Development.
                </p>
              </div>
            </div>
            <img
              src="/images/gifs/Computer.gif"
              alt="computer"
              className="aspect-square bg-cover"
            />
          </div>

          <div className="my-28 flex flex-col gap-8 text-lg">
            <h1 className="text-3xl font-bold">About</h1>
            <div className="flex items-center justify-between">
              <img
                src="/images/gifs/Kenji-Idle.gif"
                alt="game"
                className="aspect-square bg-cover"
              />

              <p className="md:max-w-2xl">
                I enjoy playing video games and learning new things. I'm always
                looking for new ways to improve my game development skills. I am
                mostly interested in the design aspect of game development and
                have been improving these skills with some of the projects i
                have done.
              </p>
            </div>
            <div className="flex items-center justify-between">
              <img
                src="/images/gifs/WebDev.gif"
                alt="web"
                className="aspect-square"
              />
              <p className="md:max-w-2xl">
                I enjoy learning new things and solving problems. I'm always
                looking for new ways to improve my coding skills. I really enjoy
                making the website look asethetic as possible.
              </p>
            </div>
          </div>

          <section className="my-10 flex flex-col pb-20">
            <div className="grid gap-4 lg:grid-cols-2">
              {projects.map((project) => (
                <ProjectCards key={project._id} {...project} />
              ))}
            </div>
          </section>
        </div>
      </main>
    </div>
  );
}

export default Home;

// internal components

function ProjectCards({
  title,
  url,
  shortDescription,
  tags,
  date,
  images,
}: Project) {
  return (
    <Link href={url}>
      <a>
        <div className="flex h-80 flex-col gap-2 overflow-hidden rounded-none p-2 text-sm shadow-lg">
          <h1>{title}</h1>
          <div>{shortDescription}</div>
          <div className="flex gap-2">
            {tags.map((tag) => (
              <span key={tag} className="">
                {tag}
              </span>
            ))}
          </div>
        </div>
      </a>
    </Link>
  );
}
