import Head from "next/head";

function Home() {
  return (
    <div>
      <Head>
        <title>Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/Ramen.ico" />
      </Head>

      <main className="container mx-auto flex flex-col gap-4">
        <div className="my-1 sm:mx-4 md:mt-20">
          <div className="flex justify-between gap-36">
            <div className="flex flex-col gap-4 text-left text-3xl">
              <h1 className="font-semibold">Welcome</h1>
              <div className="flex gap-4">
                <p>
                  Hi there! I'm Danny Jiang, a passionate web/game developer.
                  <br />
                  I'm a graduate at the Unversity of Technology Sydney studied a
                  Bachelor of Science in Games Development.
                </p>
              </div>
            </div>
            <div className="w-64">
              <img
                src="/Computer.gif"
                alt="computer"
                className="aspect-square bg-cover"
              />
            </div>
          </div>

          <div className="my-28 flex flex-col gap-8">
            <h1 className="text-3xl font-semibold">About</h1>
            <div className="flex gap-4">
              <div className="w-60">
                <img
                  src="/Kenji-Idle.gif"
                  alt="game"
                  className="aspect-[4/3] bg-cover"
                />
              </div>
              <p>
                I enjoy playing video games and learning new things. I'm always
                looking for new ways to improve my game development skills. I am
                mostly interested in the design aspect of game development and
                have been improving these skills with some of the projects i
                have done.
              </p>
            </div>
            <div className="flex gap-4">
              <div className="w-60  bg-cover">
                <img src="/WebDev.gif" alt="web" className="aspect-[4/3]" />
              </div>
              <p>
                I enjoy learning new things and solving problems. I'm always
                looking for new ways to improve my coding skills. I really enjoy
                making the website look asethetic as possible.
              </p>
            </div>
          </div>

          <section></section>
        </div>
      </main>
    </div>
  );
}

export default Home;

// internal components

function ProjectCards() {}
